### ISSUE TITLE
What does "different activities" mean for the CP/FTP calculation

### ISSUE THREAD

**Issue by f1r2a** [f1r2a/SPCs#4]
**Reported by**
Alex

**Describe the bug**
Would it make things clearer if the name of this calculation or somewhere in the Next Steps section made it more explicit what “different activities” means? For new users, I could see the two being confusing because they appear the same/similar. For example saying this calculation is for activities that happen on separate days versus same-day (like for the CP test calculation). What about “... from different activities/days”? Or just “days”?

**Expected behavior**
Perhaps change the name to "Calculate FTP/CP and RWC (W') using maximal efforts from different **days**"

**Comment by f1r2a** [comment]
Waiting for input from Mikael and Steve P

**Comment by mlonn** [comment]
> SPC QA5 splits the CP/FTP calculation into "Calculate FTP/CP and RWC (W') from a CP test" and "Calculate FTP/CP and RWC (W') using maximal efforts from different activities".

Is the second of these clearer if we call it "Calculate FTP/CP and RWC (W') using maximal efforts from different days"? It's most likely that maximal efforts on one day will route through the CP test calculation, while changing activities to days sets an expectation that the activities will be from different days and therefore an activity date should be entered. What do you think <@U0115GBDJE5> and <@U011CAL5YP6>?
<sub>[View in Slack](https://superpowercalculator.slack.com/archives/C011BD2JWQM/p1588227116002900)</sub>

**Comment by mlonn** [comment]
Maybe it should just be called 
> Calculate FTP/CP and RWC (W') from maximal efforts
or
> Calculate FTP/CP and RWC (W') from 2 or more maximal efforts

Since the other one is > Calculate FTP/CP and RWC (W') **from** a CP test

**Comment by f1r2a** [comment]
Left as-is for SPCs v4 release. We'll take feedback after release and revisit (if needed) prior to next release.
